apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-comment
  labels:
    app: predict-comment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predict-comment
  template:
    metadata:
      labels:
        app: predict-comment
    spec:
      containers:
      - name: predict-comment
        image: 21520623/predict-comment:latest
        ports:
        - containerPort: 5609
---
apiVersion: v1
kind: Service
metadata:
  name: predict-comment-svc
  labels:
    app: predict-comment
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5609
  selector:
    app: predict-comment
